### ISSUE TITLE
TypeError: Cannot read property 'speedIndex' of undefined

### ISSUE THREAD

**Issue by philbooth** [nature/webpagetest-mapper#9]
Spotted by @mdi, when specifying `--resultIds 150505_60_C1B`.

**Comment by philbooth** [comment]
Fixed and published as 0.1.1 on npm.

The cause was an unexpected difference in the data format for those results. It's possible that other results could turn up similar problems elsewhere, so I may need to fix them on a case-by-case basis. Let me know if you see any more! :)

**Comment by mdi** [comment]
It's working great. Thanks! :)

**Comment by raghulraj** [comment]
Hi @philbooth ,

I am still getting the error. Please check in html-comparison also.

2015-06-20 15:30:21 ERROR webpagetest-mapper: failed to map result 150xxx_xx_xx [Home page]; Cannot read property 'firstView' of undefined
TypeError: Cannot read property 'speedIndex' of undefined
    at getSimpleValue (/../node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:482:44)
    at getValue (/../node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:423:12)
    at filterResults (/../node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:415:12)
    at Array.filter (native)
    at mapChart (/../node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:379:35)
    at Array.map (native)
    at mapResults (/../node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:159:24)
    at Object.map (/Users/raghul22/Perf/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:129:19)
    at map (/../node_modules/webpagetest-mapper/src/index.js:170:32)
    at runMicrotasksCallback (node.js:337:7)

Thanks,
Raghul

**Comment by philbooth** [comment]
Hi @raghulraj, I need an appropriate result id in order to reproduce the issue. I've tried a few of my own results but they're not failing. Can you give me a result id?

**Comment by raghulraj** [comment]
Hi Phil,

Its working now. Could be an issue with response, while I was running. I have a request, it will be great, if you can parse these information first and repeat view [Speed index,First byte,Start render,Load,Bytes,Requests,Connections Speed] for all urls in a json format as an output option?

Thanks,
Raghul

**Comment by siddh3293** [comment]
Hi @philbooth @raghulraj 

After running the test, I am running "wptmap --resultIds 150922_T2_6,150922_YP_7  and I am getting this:


Siddharths-MacBook-Pro:~ siddharthsinha$ wptmap --resultIds 150922_T2_6,150922_YP_7
2015-09-22 16:38:40 INFO webpagetest-mapper: fetching SpeedIndex result 150922_T2_6 [undefined]
2015-09-22 16:38:40 INFO webpagetest-mapper: fetching TTFB result 150922_T2_6 [undefined]
2015-09-22 16:38:40 INFO webpagetest-mapper: fetching render result 150922_T2_6 [undefined]
2015-09-22 16:38:40 INFO webpagetest-mapper: fetching loadTime result 150922_T2_6 [undefined]
2015-09-22 16:38:40 INFO webpagetest-mapper: fetching SpeedIndex result 150922_YP_7 [undefined]
2015-09-22 16:38:40 INFO webpagetest-mapper: fetching TTFB result 150922_YP_7 [undefined]
2015-09-22 16:38:40 INFO webpagetest-mapper: fetching render result 150922_YP_7 [undefined]
2015-09-22 16:38:40 INFO webpagetest-mapper: fetching loadTime result 150922_YP_7 [undefined]
2015-09-22 16:38:41 INFO webpagetest-mapper: finished fetching SpeedIndex result 150922_YP_7 [undefined]
2015-09-22 16:38:41 INFO webpagetest-mapper: finished fetching TTFB result 150922_YP_7 [undefined]
2015-09-22 16:38:41 INFO webpagetest-mapper: finished fetching render result 150922_YP_7 [undefined]
2015-09-22 16:38:41 INFO webpagetest-mapper: finished fetching loadTime result 150922_T2_6 [undefined]
2015-09-22 16:38:41 INFO webpagetest-mapper: finished fetching render result 150922_T2_6 [undefined]
2015-09-22 16:38:41 INFO webpagetest-mapper: finished fetching SpeedIndex result 150922_T2_6 [undefined]
2015-09-22 16:38:41 INFO webpagetest-mapper: finished fetching TTFB result 150922_T2_6 [undefined]
2015-09-22 16:38:41 INFO webpagetest-mapper: finished fetching loadTime result 150922_YP_7 [undefined]
2015-09-22 16:38:41 INFO webpagetest-mapper: mapping result 150922_T2_6 [150922_T2_6]
2015-09-22 16:38:41 ERROR webpagetest-mapper: failed to map result 150922_T2_6 [150922_T2_6]; Cannot read property 'firstView' of undefined
2015-09-22 16:38:41 INFO webpagetest-mapper: mapping result 150922_YP_7 [150922_YP_7]
2015-09-22 16:38:41 ERROR webpagetest-mapper: failed to map result 150922_YP_7 [150922_YP_7]; Cannot read property 'firstView' of undefined
TypeError: Cannot read property 'speedIndex' of undefined
    at getSimpleValue (/usr/local/nodejs/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:482:44)
    at getValue (/usr/local/nodejs/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:423:12)
    at filterResults (/usr/local/nodejs/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:415:12)
    at Array.filter (native)
    at mapChart (/usr/local/nodejs/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:379:35)
    at Array.map (native)
    at mapResults (/usr/local/nodejs/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:159:24)
    at Object.map (/usr/local/nodejs/lib/node_modules/webpagetest-mapper/src/mappers/html-comparison/index.js:129:19)
    at map (/usr/local/nodejs/lib/node_modules/webpagetest-mapper/src/index.js:170:32)
    at runMicrotasksCallback (node.js:337:7)
Fatal error, exiting. 


Please guys help me out


thanks
siddharth

**Comment by rcherny** [comment]
@philbooth Pretty sure I'm seeing this or something similar crashing out on a number of these reports when I'm doing a `firstViewOnly` type set of runs.
